### ISSUE TITLE
Crashes on messages with a content type but no boundary

### ISSUE THREAD

**Issue by maz0717** [Rambomst/PHP-Bounce-Handler#5]
Error message:PHP Notice 'yii\base\ErrorException' with message 'Undefined index: boundary'

in /path/vendor/rambomst/php-bounce-handler/src/BounceHandler.php:66

Example message:
Received: from mail.here.com (LHLO mail1.there.com) (10.10.10.10) by
 mail1.mlx.net with LMTP; Wed, 10 Jan 2018 03:17:18 -0800 (PST)
Date: Wed, 10 Jan 2018 19:26:06 +0800 (WST)
From: someone@there.com
To: someone@here.com
Message-ID: <506513329.105301515583566208.JavaMail.root@zim-store02.web.westnet.com.au>
In-Reply-To: <b17a27357143a763cc067b301d2a7de3@swift.generated>
Subject: Re: Subject
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Auto-Submitted: auto-replied (zimbra; vacation)
Precedence: bulk

Some User has left Some Company.

All enquiries should be directed to email@domain.com or by ringing the office on (555) 555-1212.

Thank you.

**Comment by Rambomst** [comment]
Merged changes from #8 and released in v1.5
