### ISSUE TITLE
Boundaries ending in = causing the parsing of parts to break

### ISSUE THREAD

**Issue by maz0717** [Rambomst/PHP-Bounce-Handler#6]
A boundary of Content-Type: multipart/report; report-type=delivery-status;
 boundary="L/SKIL5D7BlmFux85YoTqBqFvSVKOmzyDczI+g==" is causing the parseBodyIntoMimeSections function to break.  

This is because there are no body parts to assign to the  $mime_section variable.

The breakage is caused by the last line in the initBounceHandler function. =\r\n is replaced with \n.  According to the library this is based on, that str_replace is no longer needed because mime parsing happens elsewhere.

**Comment by Rambomst** [comment]
Merged changes from #8 and released in v1.5
