### ISSUE TITLE
Dash instead of space in diagnostic code causing crash

### ISSUE THREAD

**Issue by maz0717** [Rambomst/PHP-Bounce-Handler#7]
550-Please turn on SMTP Authentication in your mail client, or login to the 550-IMAP/POP3 server before sending your message. mail.domain.com 550-[1.1.1.1]:44624 is not permitted to relay through this server without 550 authentication.

regex in formatStatusCode function is expecting a space.

**Comment by maz0717** [comment]
Made a mistake.  It's the regex in decodeDiagnosticCode that is expecting a space.

**Comment by Rambomst** [comment]
Merged changes from #8 and released in v1.5
